import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,readdir,rm,symlink,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createSkillStore} from '../server/skill-store.mjs';
const events=[{sequence:1,type:'TaskCompleted',actorId:'firefighter',taskId:'connect_hose',episodeId:'episode-a'},{sequence:2,type:'TaskActivated',actorId:'engineer',taskId:'operate_pump',episodeId:'episode-a'},{sequence:3,type:'MessageSent',actorId:'firefighter',episodeId:'episode-a'}];
async function fixture(options={}){const directory=await mkdtemp(join(tmpdir(),'forest-skills-')),store=await createSkillStore({directory,...options});return {directory,store};}
const lesson=(overrides={})=>({id:'keep-water-ready',title:'Keep water ready',body:'# Keep water ready\n\nWatch current pressure.',evidence:[1],parentIds:[],...overrides});
test('rejects invented evidence and success belonging to another actor',async t=>{const f=await fixture();t.after(()=>rm(f.directory,{recursive:true,force:true}));assert.deepEqual(await f.store.save('firefighter',lesson({evidence:[99]}),events),{ok:false,error:'invalid_evidence'});assert.deepEqual(await f.store.save('firefighter',lesson({evidence:[2]}),events),{ok:false,error:'invalid_evidence'});assert.deepEqual(await f.store.list('firefighter'),{ok:true,skills:[]});});
test('rejects traversal, invalid actors, cross-actor parents, and symlink skill directories',async t=>{const f=await fixture();t.after(()=>rm(f.directory,{recursive:true,force:true}));assert.equal((await f.store.save('firefighter',lesson({id:'../escape'}),events)).error,'invalid_skill');assert.equal((await f.store.read('player','keep-water-ready')).error,'invalid_actor');assert((await f.store.save('engineer',lesson({id:'pump-watch',evidence:[2]}),events)).ok);assert.equal((await f.store.save('firefighter',lesson({id:'handoff',parentIds:['pump-watch']}),events)).error,'parent_not_found');await mkdir(join(f.directory,'firefighter'),{recursive:true});await symlink(tmpdir(),join(f.directory,'firefighter','linked'));assert.equal((await f.store.read('firefighter','linked')).error,'unsafe_directory');});
test('round trips literal lesson revisions, evidence records, and immutable history',async t=>{const f=await fixture();t.after(()=>rm(f.directory,{recursive:true,force:true}));const first=lesson(),second=lesson({title:'Keep water ready under pressure',body:'# Revised\n\nCheck the live gauge.',evidence:[1,3]});assert.equal((await f.store.save('firefighter',first,events)).skill.version,1);assert.equal((await f.store.save('firefighter',second,events)).skill.version,2);const read=await f.store.read('firefighter',first.id);assert.equal(read.skill.body,second.body);assert.equal(read.skill.version,2);assert.deepEqual(read.skill.evidenceEvents,[{sequence:1,type:'TaskCompleted',actorId:'firefighter',taskId:'connect_hose',episodeId:'episode-a'},{sequence:3,type:'MessageSent',actorId:'firefighter',taskId:null,episodeId:'episode-a'}]);assert.equal((await f.store.list('engineer')).skills.length,0);const versions=await readdir(join(f.directory,'firefighter',first.id));assert.deepEqual(versions.sort(),['000001','000002']);assert.equal(await readFile(join(f.directory,'firefighter',first.id,'000001','SKILL.md'),'utf8'),first.body);});
test('rejects symlink metadata and SKILL.md files before reading',async t=>{const f=await fixture();t.after(()=>rm(f.directory,{recursive:true,force:true}));assert((await f.store.save('firefighter',lesson(),events)).ok);const version=join(f.directory,'firefighter','keep-water-ready','000001'),bodyPath=join(version,'SKILL.md'),metadataPath=join(version,'metadata.json'),outside=join(f.directory,'outside');await writeFile(outside,'{}');await rm(bodyPath);await symlink(outside,bodyPath);assert.equal((await f.store.read('firefighter','keep-water-ready')).error,'unsafe_file');await rm(bodyPath);await writeFile(bodyPath,lesson().body);await rm(metadataPath);await symlink(outside,metadataPath);assert.equal((await f.store.read('firefighter','keep-water-ready')).error,'unsafe_file');});
test('rejects cyclic revision parents',async t=>{const f=await fixture();t.after(()=>rm(f.directory,{recursive:true,force:true}));assert((await f.store.save('firefighter',lesson({id:'base'}),events)).ok);assert((await f.store.save('firefighter',lesson({id:'branch',parentIds:['base']}),events)).ok);assert.equal((await f.store.save('firefighter',lesson({id:'base',parentIds:['branch']}),events)).error,'cyclic_parent');});
test('capacity failure publishes no partial version',async t=>{const f=await fixture({maxBytes:700});t.after(()=>rm(f.directory,{recursive:true,force:true}));assert((await f.store.save('firefighter',lesson({body:'x'.repeat(200)}),events)).ok);const before=await readdir(join(f.directory,'firefighter','keep-water-ready'));const result=await f.store.save('firefighter',lesson({body:'y'.repeat(600)}),events);assert.deepEqual(result,{ok:false,error:'capacity_exceeded'});assert.deepEqual(await readdir(join(f.directory,'firefighter','keep-water-ready')),before);assert.equal((await f.store.read('firefighter','keep-water-ready')).skill.version,1);});
